version: "3"
services:
  frontend:
    image: node:alpine
    volumes:
      - ./frontend/:/app
    working_dir: /app
    depends_on:
      - backend
    environment:
      REACT_APP_API_PORT: 8888
    ports:
      - 3000:3000
    command: npm run start
  backend:
    image: node:alpine
    volumes:
      - ./backend/:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGO_HOST: mongo
      PORT: 8888
    ports:
      - 8888:8888
    command: npm run dev
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - data:/data/db
volumes:
  data:
