version: "3"
services:
  backend:
    image: node:alpine
    volumes:
      - ./backend/:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGO_HOST: mongo
    ports:
      - 3000:3000
    command: npm run dev
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - data:/data/db
volumes:
  data:
